### ISSUE TITLE
Request to add Hindi Reading Comprehension dataset

### ISSUE THREAD

**Issue by erzaliator** [AI4Bharat/indicnlp_catalog#129]
README.md can include [HindiRC](https://github.com/erzaliator/HindiRC-Data), a non-factoid QA dataset. 

Reference: https://www.researchgate.net/publication/342424208_HindiRC_A_Dataset_for_Reading_Comprehension_in_Hindi

**Comment by anoopkunchukuttan** [comment]
Merged
