### ISSUE TITLE
PHINC: A Parallel Hinglish Social Media Code-Mixed Corpus for Machine Translation

### ISSUE THREAD

**Issue by GokulNC** [AI4Bharat/indicnlp_catalog#130]
13.5k parallel annotated sentences:
https://zenodo.org/record/3605597#.YVKJ2bgzZEY

**Comment by GokulNC** [comment]
6k parallel sentences from IIIT:
https://github.com/mrinaldhar/en-hi-codemixed-corpus

Paper: https://aclanthology.org/W18-3817.pdf

**Comment by GokulNC** [comment]
CALCS 2021 Eng-Hinglish dataset: (10k pairs)
https://code-switching.github.io/2021#shared-task-1

**Comment by anoopkunchukuttan** [comment]
done
