### ISSUE TITLE
AI4Bharat Cross-lingual Semantic Textual Similarity

### ISSUE THREAD

**Issue by anoopkunchukuttan** [AI4Bharat/indicnlp_catalog#146]
30k examples between English and 12 Indian languages judged as per Semeval 2016 guidelines

Paper: https://arxiv.org/abs/2104.05596
Dataset: https://storage.googleapis.com/samanantar-public/human_annotations.tsv

**Comment by arnoldsachith** [comment]
Hello, I was looking for Semantic Similarity Dataset which is mentioned in this website: https://ai4bharat.iitm.ac.in/samanantar but it seems like the data has been removed. I also tried the link mentioned in your comment on Jan 15 2022. Seems like it is not available, The link to paper which says the data was released for public : https://arxiv.org/abs/2104.05596 .  Can you please help me out in getting the data. It will be helpful in carrying out my research works.

**Comment by iampushpdeep** [comment]
Same issue here. Can't access this data.

**Comment by jaygala24** [comment]
We checked with the team who worked on [Samanantar Paper](https://arxiv.org/abs/2104.05596). However, it seems that we don't have the available mirror link. We will get back to this issue once we have the mirror link. Thank you!

**Comment by jaygala24** [comment]
@iampushpdeep @arnoldsachith 
You can download the Semantic Similarity Dataset from the following link:
https://github.com/AI4Bharat/indicTrans#sts-benchmark
