### ISSUE TITLE
Parallel Corpora for 6 Indian Languages

### ISSUE THREAD

**Issue by maharajbrahma** [AI4Bharat/indicnlp_catalog#151]
ISLRN Link: [http://www.islrn.org/resources/657-350-757-058-6/](http://www.islrn.org/resources/657-350-757-058-6/)

Languages: Bengali, English, Hindi, Malayalam, Tamil, Telugu, Urdu to English
Size: 197,000 sentences

**Comment by GokulNC** [comment]
Thanks. This one is probably same as [MTurk Indian Parallel Corpus](https://github.com/joshua-decoder/indian-parallel-corpora) (which is already mentioned in the README).
The stats seems to match with [the 2012 paper](https://aclanthology.org/W12-3152.pdf), although the above link seems to be recent.

**Comment by maharajbrahma** [comment]
Seems like it. I missed it in README.
