### ISSUE TITLE
IISc-MILE ASR Corpus

### ISSUE THREAD

**Issue by GokulNC** [AI4Bharat/indicnlp_catalog#184]
Links to corpus:
- [Kannada dataset](http://www.openslr.org/126/)
- [Tamil dataset](http://www.openslr.org/127/)

Other links:
- [Paper](https://arxiv.org/abs/2207.13331)
- [Announcement](https://www.linkedin.com/posts/ramakrishnan-a-g-4b78783_data-india-training-activity-6960561345989632001-SfpD)

**Comment by anoopkunchukuttan** [comment]
Done
