### ISSUE TITLE
Malayalam Speech

### ISSUE THREAD

**Issue by anoopkunchukuttan** [AI4Bharat/indicnlp_catalog#19]
https://www.kaggle.com/kurianbenoy/malayalam-multispeaker-speech-data-set

**Comment by kavyamanohar** [comment]
This Kaggle repository mirrors the data from http://www.openslr.org/resources/63/

**Comment by anoopkunchukuttan** [comment]
Thanks for pointing.

**Comment by anoopkunchukuttan** [comment]
Added
