### ISSUE TITLE
TeSum: Telugu Abstractive Summarization

### ISSUE THREAD

**Issue by anoopkunchukuttan** [AI4Bharat/indicnlp_catalog#224]
[TeSum: Human-Generated Abstractive Summarization Corpus for Telugu](https://aclanthology.org/2022.lrec-1.614.pdf)

Link to dataset broken - https://github.com/manshri/TeSum/

**Comment by ashokurlana** [comment]
Please find the TeSum dataset:
https://ltrc.iiit.ac.in/showfile.php?filename=downloads/teSum/

**Comment by anoopkunchukuttan** [comment]
Thanks, I noticed that the download file is named as a zip, but is actually a tgz archive.

**Comment by anoopkunchukuttan** [comment]
- Telugu Abstractive Summarization dataset containing 20k+ article-summary pairs (with a 80,20,20% train/valid/test split). That's a fairly big, manually created dataset. 
- The summaries were collected via a crowdsourced effort with detailed guidelines and quality control to ensure high quality. 
- Unlike other automatically mined summarization datasets, which pair article with highlights as summary, the summaries are manually written. 
- 90k summaries were thus collected, and finally 20k were accepted after quality control. The scale and co-ordinaltion of the effort is laudable. 
- The paper documents the guidelines and process in detail and will be a useful reference for other interested in summarization dataset creation guidelines. 

Paper Link: https://aclanthology.org/2022.lrec-1.61 Presented at LREC 2022 

Dataset Link: https://ltrc.iiit.ac.in/showfile.php?filename=downloads/teSum/

Work from IIIT Hyderabad

**Comment by kavyamanohar** [comment]
The paper link is:  https://aclanthology.org/2022.lrec-1.614/

**Comment by anoopkunchukuttan** [comment]
Thanks for pointing out - that was a mistake

**Comment by Rushikiran7** [comment]
> Please find the TeSum dataset: https://ltrc.iiit.ac.in/showfile.php?filename=downloads/teSum/

Error while  opening the zip folder

**Comment by ashokurlana** [comment]
@Rushikiran7 There is some issue with the zip folder, please find the TeSum dataset here: https://drive.google.com/file/d/1WOoa5eevubODl1pVDZ-1POBNXeAQN5a1/view?usp=sharing

**Comment by Rushikiran7** [comment]
@ashokurlana Thankyou sir for the dataset, If you are working on any exciting projects let me know I will love to work
