### ISSUE TITLE
Telugu Raw Corpus : Request for Addition

### ISSUE THREAD

**Issue by neshkatrapati** [AI4Bharat/indicnlp_catalog#51]
This is the link for a raw telugu corpus. It also contains a word2vec model trained with it : https://drive.google.com/drive/folders/0B7LLASJiB2m6cDVzbnNjUVZ5dUE?usp=sharing

It contains 2,23,86,073 Unique sentences and it is the largest Telugu corpus I know of.

**Comment by anoopkunchukuttan** [comment]
Thanks, will add this.

**Comment by anoopkunchukuttan** [comment]
Added. Can you tell what license is the the corpus released under?

**Comment by neshkatrapati** [comment]
Please change the URL : https://drive.google.com/drive/folders/1fEt7aIzYWGQKto3Nt51M5CdjtzxMqdCz?usp=sharing

**Comment by anoopkunchukuttan** [comment]
Can you make the change and make a pull request

**Comment by neshkatrapati** [comment]
Yes. Will do it thanks.
