### ISSUE TITLE
HiQuAD

### ISSUE THREAD

**Issue by anoopkunchukuttan** [AI4Bharat/indicnlp_catalog#62]
Hindi QA dataset

Link: https://www.cse.iitb.ac.in/~ganesh/HiQuAD/clqg/clqg_data.tar.gz
Paper: https://www.cse.iitb.ac.in/~ganesh/papers/acl2019a.pdf

Contributed by: Ratish Puduppully

**Comment by ritwikmishra** [comment]
SQuAD is factoid based QA system
where each question is accompanied by a small snippet (paragraph) from which a short answer is extracted

this data very different

they have only Question-Answer pairs
without any snippet

for eg
Q गाँधीजी अपने दक्षिण अफ्रिका प्रवास से वापस देश कब लौटे ? 
A गांधीजी ९ जनवरी , १९१५ को अपने दक्षिण अफ्रिका प्रवास से वापस देश लौटे

that's it

**Comment by anoopkunchukuttan** [comment]
done
