### ISSUE TITLE
MuRIL

### ISSUE THREAD

**Issue by anoopkunchukuttan** [AI4Bharat/indicnlp_catalog#64]
https://tfhub.dev/google/MuRIL/1

**Comment by maninuthi** [comment]
Is the model architecture exactly the same as traditional bert? 
I got the following error and don't know how to solve it.
 Error : ValueError: Layer #0 (named “bert”) expects 199 weight(s), but the saved weights have 197 element(s).

**Comment by anoopkunchukuttan** [comment]
@maninuthi: please contact the MuRIL developers for details. I don't know the details of the architecture.

**Comment by anoopkunchukuttan** [comment]
done
