### ISSUE TITLE
en-mr: parallel data not aligned

### ISSUE THREAD

**Issue by Aditi138** [AI4Bharat/indicnlp_catalog#71]
The en-mr parallel data (http://preon.iiit.ac.in/~jerin/resources/datasets/pib-v0.tar) doesn't seem to be 1:1 aligned. Is there a mapping file available?

**Comment by GokulNC** [comment]
Hi. We are not sure about that since it's not a work done by us.
It would be better if you can ask it here in their official repo:
https://github.com/shashanksiripragada/pib-crawl

Or you can even try emailing their research group:
http://preon.iiit.ac.in/~jerin/bhasha/

Best regards!

**Comment by GokulNC** [comment]
BTW, you can also first check the latest version of the PIB dump here:
http://preon.iiit.ac.in/~jerin/resources/datasets/
