### ISSUE TITLE
Need to discuss the eligibility of adding the below resources

### ISSUE THREAD

**Issue by sagorbrur** [AI4Bharat/indicnlp_catalog#98]
Hi,
Thanks for this beautiful catalog. 
I have created some resources for Bengali. I am describing one by one according to index and language
- Libraries and Tools
  - [bnlp](https://github.com/sagorbrur/bnlp) (Bengali)
  - [codeswitch](https://github.com/sagorbrur/codeswitch) (hindi-english, nepali-english)
- Models
  - [Bangla BERT](https://github.com/sagorbrur/bangla-bert) (Bengali)
  
Please check these details and if these details are eligible for adding here, please add them.
Regards

**Comment by anoopkunchukuttan** [comment]
Hi, 

This is useful. Please make the changes and raise a PR and I will incorporate it into the catalog.

Anoop.

**Comment by sagorbrur** [comment]
Thanks @anoopkunchukuttan 
I will create a PR.
Regards
